// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-xLgQOR_ZT_G1X3PQXMJLDcxLEh8M-Iw',
    appId: '1:872987056302:web:84981e2f385aaa8b45353f',
    messagingSenderId: '872987056302',
    projectId: 'social-project-88f1c',
    authDomain: 'social-project-88f1c.firebaseapp.com',
    storageBucket: 'social-project-88f1c.appspot.com',
    measurementId: 'G-B2XWX78XX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKHLwzfzQSnjRpiHHsWSzU8iOxVDTqHqg',
    appId: '1:872987056302:android:0334b7c4049b4d7545353f',
    messagingSenderId: '872987056302',
    projectId: 'social-project-88f1c',
    storageBucket: 'social-project-88f1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAteSr2Vv1aIJ0WD4eMaS0MdzFGDkGHj3w',
    appId: '1:872987056302:ios:133479617aba1b1a45353f',
    messagingSenderId: '872987056302',
    projectId: 'social-project-88f1c',
    storageBucket: 'social-project-88f1c.appspot.com',
    androidClientId: '872987056302-girsn4mhaa7qeqd94b58sltst8s35kfo.apps.googleusercontent.com',
    iosClientId: '872987056302-62s5u1mb3lp47uh6rvukkeqtbn5i69dd.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAteSr2Vv1aIJ0WD4eMaS0MdzFGDkGHj3w',
    appId: '1:872987056302:ios:133479617aba1b1a45353f',
    messagingSenderId: '872987056302',
    projectId: 'social-project-88f1c',
    storageBucket: 'social-project-88f1c.appspot.com',
    androidClientId: '872987056302-girsn4mhaa7qeqd94b58sltst8s35kfo.apps.googleusercontent.com',
    iosClientId: '872987056302-62s5u1mb3lp47uh6rvukkeqtbn5i69dd.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );
}
